name: Build

on:
  workflow_dispatch:
    inputs:
      tags:
        default: 'regular'
        required: false
        description: 'Run tests with specific tag(s)'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm ci
      - name: Init Playwright
        run: npx playwright install --with-deps
      - name: Test Playwright
        run: npx playwright test --grep @{{ github.inputs.tags }}

      - name: Allure history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Allure Publish
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history